query {
  companiespaged (
    orderBy: { path: "CompanyDataScore.FilingDate", descending: true }
    where: { groupedExpressions: [
      { path: "HasCompanyDataScore", comparison: equal, value: "true" } # Required
      { path: "PrimaryIndex.Name", comparison: in, value: ["S&P 500", "Russell 1000", "S&P 400", "S&P 600", "Russell 2000"] } # Delete as appropriate
      { path: "CompanyDataScore.FinancialDocumentType", comparison: in, value: ["10-K","10-Q"] } # Delete as appropriate
      { path: "CompanyDataScore.ScorePublishedDate", comparison: lessThan, value: "2023-10-12T12:00:00" } # UTC. Vary this as required to reflect your last poll.
    ]}
    first: 10 # Paging value. Required. Please keep to < 500,
    #skip: 30 # Optional value to skip completed.
  ) {
    totalCount
    edges {
      node {
        Company: name
        Ticker: primaryTicker { name }
        CIKCode: cIK
        PrimaryIndex: primaryIndex { name }
        CompanyDataScore: companyDataScore {
            FilingDate: filingDate
            ScorePublishedDate: scorePublishedDate
            FiscalPeriod: period {
                year,
                quarter
            }
            DocumentType: financialDocumentType
            Document: document {
                DataScore: dataScore
                ScorableWordCount: words
                FragmentsCount: fragmentsCount
                DeceptiveFragmentsCount: deceptiveFragmentsCount
                DeceptiveFragmentsPercentage: deceptiveFragmentsPercentage
                TruthfulFragmentsCount: truthfulFragmentsCount
                TruthfulFragmentsPercentage: truthfulFragmentsPercentage
                LongTermFocus: longTermFocus
                ShortTermFocus: shortTermFocus
                InternalFocus: internalFocus
                ExternalFocus: externalFocus
            }
            DeceptiveFragmentsAverageScore: fragmentsNegativeAverage
            TruthfulFragmentsAverageSCore: fragmentsPositiveAverage
            DatabaseRank: dATAbaseComparison { rank }
            FinancialUncertainty: financialUncertainty,
            CompanySectionDataScore: companySectionDataScores {
                SectionID: sectionID # Expect 2 for MD&A 10-Q, 7 for 10-K
                FilingDate: filingDate
                FiscalPeriod: period {
                    year
                    quarter
                }
                DocumentType: financialDocumentType
                Document: document {
                    DataScore: dataScore,
                    ScorableWordCount: words,
                    FragmentsCount: fragmentsCount,
                    DeceptiveFragmentsCount: deceptiveFragmentsCount
                    DeceptiveFragmentsPercentage: deceptiveFragmentsPercentage
                    TruthfulFragmentsCount: truthfulFragmentsCount
                    TruthfulFragmentsPercentage: truthfulFragmentsPercentage
                    LongTermFocus: longTermFocus
                    ShortTermFocus: shortTermFocus
                    InternalFocus: internalFocus
                    ExternalFocus: externalFocus
                }
                FinancialUncertainty: financialUncertainty
            }
        }
      }
    }
  }
}
